<a href="https://colab.research.google.com/github/shayari21/100DaysOfML/blob/master/Multi_UAV(inc_takeoff_costs).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 29 20:36:16 2019

@author: admin
"""

import numpy as np

trip_distance=[120,100,140,90,180,90]
trip_cord=[[10,130],[10,110],[80,220],[100,190],[40,220],[130,220]]
u_alt=1800
r_alt=[0,100,300,250,200,200,100]
r_pos=[10,50,90,105,130,180,220]
uav=[]
total_d=230
d1=0
d2=0
d=0
cost=np.zeros((total_d,total_d))
min_cost=np.zeros((7,7))
d1_min=np.zeros((7,7))
d2_min=np.zeros((7,7))
item='NA'
iter_1=0

for x in range(len(r_pos)):
    for y in range(len(r_pos)):
        x_1=r_pos[x]
        y_1=r_pos[y]
        for i in range(total_d):
            for j in range(total_d):
                allocated_agent=[]
                for m in range(len(trip_cord)):
                    x1=trip_cord[m][0]
                    #print(x1)
                    x2=trip_cord[m][1]
            
                    if x1 <= x_1 <= x2:
                        allocated_agent.insert(m,"UAV1")
                    elif x1 <= y_1 <= x2:
                        allocated_agent.insert(m,"UAV2")
            #print(allocated_agent)
                    if (len(allocated_agent)!=len(trip_cord)):
                        cost[i][j]=((u_alt-r_alt[x])*20+ (u_alt-r_alt[y])*20)
                    else:
                        iter_1=iter_1+1
                        d1=abs(i-x_1)
                        d2=abs(j-y_1)
                        d=d1+d2
                        cost[i][j]=(d*10+ (u_alt-r_alt[x])*20+ (u_alt-r_alt[y])*20)
        for i in range(len(cost)):
            for j in range(len(cost[i])):
                if (min_cost[x][y]==0):
                    min_cost[x][y]=cost[i][j]
                    d1_min[x][y]=i
                    d2_min[x][y]=j
                elif(min_cost[x][y]>cost[i][j] and cost[i][j]!=0):
                    min_cost[x][y]=cost[i][j]
                    d1_min[x][y]=i
                    d2_min[x][y]=j
                    
print(min_cost)
print(d1_min)
print(d2_min)
min_cost_f=0
d1_min_f=0
d2_min_f=0
for i in range(len(min_cost)):
    for j in range(len(min_cost[i])):
        if (min_cost_f==0):
            min_cost_f=min_cost[i][j]
            d1_min_f=d1_min[i][j]
            d2_min_f=d2_min[i][j]
        elif(min_cost_f>min_cost[i][j] and min_cost[i][j]!=0):
            min_cost_f =min_cost[i][j]
            d1_min_f=d1_min[i][j]
            d2_min_f=d2_min[j][j]
print(min_cost_f)
print(d1_min_f)
print(d2_min_f)
allocated_agent=[]
for i in range(len(trip_cord)):
    
    x1=trip_cord[i][0]
    x2=trip_cord[i][1]
    if x1 <= d1_min_f <= x2:
        allocated_agent.insert(i,"UAV1")
    elif x1 <= d2_min_f <= x2:
        allocated_agent.insert(i,"UAV2")
    else:
        allocated_agent.insert(i,"NA")
print(allocated_agent)
                


[[72000. 70000. 66000. 67000. 68000. 68000. 70000.]
 [70000. 68000. 64000. 65000. 66000. 66000. 68000.]
 [66000. 64000. 60000. 61000. 62000. 62000. 64000.]
 [67000. 65000. 61000. 62000. 63000. 63000. 65000.]
 [68000. 66000. 62000. 63000. 64000. 64000. 66000.]
 [68000. 66000. 62000. 63000. 64000. 64000. 66000.]
 [70000. 68000. 64000. 65000. 66000. 66000. 68000.]]
[[  0.   0.   0.   0.  10.  10.   0.]
 [  0.   0.   0.   0.  50.  50.   0.]
 [  0.   0.   0.   0.  90.  90.   0.]
 [  0.   0.   0.   0. 105. 105. 105.]
 [130. 130. 130. 130.   0.   0.   0.]
 [180. 180. 180. 180.   0.   0.   0.]
 [  0.   0.   0. 220.   0.   0.   0.]]
[[  0.   0.   0.   0. 130. 180.   0.]
 [  0.   0.   0.   0. 130. 180.   0.]
 [  0.   0.   0.   0. 130. 180.   0.]
 [  0.   0.   0.   0. 130. 180. 220.]
 [ 10.  50.  90. 105.   0.   0.   0.]
 [ 10.  50.  90. 105.   0.   0.   0.]
 [  0.   0.   0. 105.   0.   0.   0.]]
60000.0
0.0
0.0
['NA', 'NA', 'NA', 'NA', 'NA', 'NA']
